title: megabirthday.me
permalink: pretty
timezone: Europe/London
description: Celebrate every 1,000 days of life
url: https://megabirthday.me
repository: Vazool/megabirthday
author: John Crook

# Social defaults
twitter_username: megabirthday_me

plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima

# Navigation for the minima theme
minima:
  skin: megabirthday
  social_links:
    - { platform: github, user_url: "https://github.com/Vazool/megabirthday" }

# Collections and defaults (posts already work out of the box)
markdown: kramdown
